"""Add branch_id to user and branches table

Revision ID: 5203b63ac215
Revises: 008
Create Date: 2026-03-31 22:56:17.518263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5203b63ac215'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.drop_constraint(op.f('uq_notifications_ref_type'), 'notifications', type_='unique')
    op.add_column('teams', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'teams', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'branch_id')
    op.create_unique_constraint(op.f('uq_notifications_ref_type'), 'notifications', ['reference_type', 'reference_id', 'type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_table('branches')
    # ### end Alembic commands ###
